---
jobs:
  - name: 'Make a curl Request on all *release events to dev workloads'
    match:
      events: ['release', 'autorelease']
      workloads: ['*-dev']
    docker:
      image: curlimages/curl
      command: ['/usr/bin/curl']
      args: ['https://github.com']
